[package]
name = "angelus/scriptexecute"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
rodux = "roblox/rodux@3.0.0"
roact = "roblox/roact@1.4.4"
roact-rodux = "roblox/roact-rodux@0.3.0"
spring = "brittonfischer/spring@0.1.0"
roact-hooks = "kampfkarren/roact-hooks@0.4.1"
roact-spring = "chriscerie/roact-spring@1.0.1"